### ISSUE TITLE
Error Fuente Roboto - Título del Website

### ISSUE THREAD

**Issue by Angarsk8** [sergiotru07/loopa-website#1]
Hola Sergio,

La fuente del título `h1` de la página principal no está renderizándose bien, como puedes ver en la siguiente imagen:

<img width="1280" alt="captura de pantalla 2015-12-11 a las 12 04 23 a m" src="https://cloud.githubusercontent.com/assets/11448559/11736825/bc3afd5c-9fa0-11e5-8f90-a37c41cefd52.png">

Lo curioso es que inspeccionando el código css en la consola de chrome, veo que al remover la declaración que le aplica el estilo a la fuente de ese elemento, lo renderiza correctamente!! Como podés ver en la siguiente imagen:

<img width="1280" alt="captura de pantalla 2015-12-11 a las 12 44 03 a m" src="https://cloud.githubusercontent.com/assets/11448559/11736861/f981af9e-9fa0-11e5-976f-6435f7a6116c.png">

No sé por qué se estaría presentando este error.

**Comment by sergiotru07** [comment]
Hola Andrés.
Hice la respectiva revisión y el problema se debía a que había escrito mal en nombre de la fuente que le había asignado a esa clase. Dado que todo el documento maneja `Roboto`, opté por eliminar la propiedad `font-family` para esa clase y simplemente se maneja el grosor de la tipografía con la propiedad `font-size`.
Problema solucionado
