### ISSUE TITLE
Espacio entre el botón de registro y links del Navbar

### ISSUE THREAD

**Issue by Angarsk8** [sergiotru07/loopa-website#2]
Hola Sergio,

Veo que el botón de registro del website está muy pegado al último link en la barra de navegación, podrías intentar espaciarlo un poco a la derecha para evitar ese inconveniente, bien sea con padding o con margin. 

<img width="1118" alt="barra de navegacion" src="https://cloud.githubusercontent.com/assets/11448559/11736939/ca276512-9fa1-11e5-8043-0d41ee0a3484.png">

**Comment by sergiotru07** [comment]
Solucionado. 
Adicionalmente, cambié la altura de la `navbar`, pasando de `84px`a `64px` para desktop y de `64px` a `54px`en móviles.

![image](https://cloud.githubusercontent.com/assets/13666179/11737261/87766e62-9fa5-11e5-82f8-455a76ba7545.png)
