### ISSUE TITLE
Problema Tamaño Imágenes Sección Features

### ISSUE THREAD

**Issue by Angarsk8** [sergiotru07/loopa-website#9]
Probando la página en diferentes navegadores me di cuenta que en Firefox se presenta un inconveniente con el tamaño de las imágenes de las cartas en la sección de features. El problema es que las imágenes se ven distorsionadas en casi todas las resoluciones o viewports, tal como se muestra en las siguiente imágenes:

<img width="1280" alt="captura de pantalla 2016-01-07 a las 9 59 00 p m" src="https://cloud.githubusercontent.com/assets/11448559/12189236/f6956e70-b589-11e5-9168-1d084288b299.png">
<img width="1280" alt="captura de pantalla 2016-01-07 a las 9 59 16 p m" src="https://cloud.githubusercontent.com/assets/11448559/12189237/f696e5fc-b589-11e5-89e1-695f3d147637.png">
<img width="1280" alt="captura de pantalla 2016-01-07 a las 9 59 34 p m" src="https://cloud.githubusercontent.com/assets/11448559/12189238/f698efdc-b589-11e5-802d-39f78a512ccd.png">

Quedo atento a tu respuesta.

**Comment by Angarsk8** [comment]
Hola Sergio, 

Logré corregir el error en el commit [49](https://github.com/sergiotru07/loopa-website/commit/d2805e987bdcfc9e17a65796bfc7bd5a7161d2d9).

Gracias,

**Comment by sergiotru07** [comment]
ok
